/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import React, { useEffect, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { MeshStandardMaterial } from "three";

export default function Hornet({selectedCategory, selectedColor, lastColors,  ...props}) {
  const { nodes, materials } = useGLTF('https://mege707.github.io/guitar-3d/medias/Hornet.glb')

  const getColorForCategory = (category) =>
    lastColors[category] || "#F0EBCD";

  // 6) Şimdi, mesh’ler için MeshStandardMaterial’ları oluşturuyoruz:
  const guitarBodyMaterial = new MeshStandardMaterial({
    color: getColorForCategory("Guitar Body"),
    roughness: 0.4,
    metalness: 0.1,
  });
  const guitarPickguardMaterial = new MeshStandardMaterial({
    color: getColorForCategory("Pickguard"),
    roughness: 0.4,
    metalness: 0.1,
  });
  const guitarButtonsMaterial = new MeshStandardMaterial({
    color: getColorForCategory("Buttons"),
    roughness: 0.4,
    metalness: 0.1,
  });
  const guitarNeckMaterial = new MeshStandardMaterial({
    color: getColorForCategory("Guitar Neck"),
    roughness: 1,
    metalness: 0.1,
  });

  return (
    <group {...props} dispose={null}>
      <group position={[0.05, 0.3, 0]} scale={[0.03, 0.03, 0.03]} rotation={[-Math.PI/1.1, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Hornet01.geometry}
          material={guitarBodyMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Hornet01_1.geometry}
          material={guitarButtonsMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Hornet01_2.geometry}
          material={materials['Metal Pale Grey Edgewear']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Hornet01_3.geometry}
          material={guitarNeckMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Hornet01_4.geometry}
          material={guitarPickguardMaterial}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/Hornet.glb')