/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import React, { useEffect, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { MeshStandardMaterial } from "three";

export default function Wasp({selectedCategory, selectedColor, lastColors ,...props}) {
  const { nodes, materials } = useGLTF('https://mege707.github.io/guitar-3d/medias/Wasp.glb')



  const getColorForCategory = (category) =>
    lastColors[category] || "#F0EBCD";

  // 6) Şimdi, mesh’ler için MeshStandardMaterial’ları oluşturuyoruz:
  const guitarBodyMaterial = new MeshStandardMaterial({
    color: getColorForCategory("Guitar Body"),
    roughness: 0.4,
    metalness: 0.1,
  });
  const guitarPickguardMaterial = new MeshStandardMaterial({
    color: getColorForCategory("Pickguard"),
    roughness: 0.4,
    metalness: 0.1,
  });
  const guitarButtonsMaterial = new MeshStandardMaterial({
    color: getColorForCategory("Buttons"),
    roughness: 0.4,
    metalness: 0.1,
  });
  const guitarNeckMaterial = new MeshStandardMaterial({
    color: getColorForCategory("Guitar Neck"),
    roughness: 1,
    metalness: 0.1,
  });

  return (
    <group {...props} dispose={null}>
      <group position={[-0.48 , 0.15, 0]} scale={[0.013, 0.013, 0.013]} rotation={[-Math.PI/2.2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wasp01.geometry}
          material={materials['Metal Pale Grey Edgewear.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wasp01_1.geometry}
          material={guitarButtonsMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wasp01_2.geometry}
          material={guitarBodyMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wasp01_3.geometry}
          material={guitarPickguardMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wasp01_4.geometry}
          material={guitarNeckMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wasp01_5.geometry}
          material={materials['White painted metal']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/Wasp.glb')