/*
  Auto-generated by: https://github.com/pmndrs/gltfjsx
  */

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { MeshStandardMaterial } from "three";

export default function Modell(props) {
  const { nodes, materials } = useGLTF("medias/gitarraaa.glb");

  const turuncuMat = new MeshStandardMaterial({
    color: "#ff6600", // turuncu renk
    metalness: 0.2, // az metalik
    roughness: 0.5, // hafif matlık
  });

  const sapMat = new MeshStandardMaterial({
    color: "#F0EBCD",
    roughness: 0.4,
    metalness: 0.1,
  });

  return (
    
      <group {...props} dispose={null}>
        <group scale={0.015} position={[0, 1.38, 0]} rotation={[0, 0, 0]}>
          <mesh /*gitar perdeleri*/
            castShadow
            receiveShadow
            geometry={nodes.honeybee3710.geometry}
            material={materials["Metal Pale Grey Edgewear.004"]}
          />
          <mesh /*humbuckerlar +  ses düğmeleri*/
            castShadow
            receiveShadow
            geometry={nodes.honeybee3710_1.geometry}
            material={materials["Frozen white metal"]}
          />
          <mesh /*gitar kulakçıkları*/
            castShadow
            receiveShadow
            geometry={nodes.honeybee3710_2.geometry}
            material={materials["Metal Pale Grey Edgewear"]}
          />
          <mesh /*gitar telleri*/
            castShadow
            receiveShadow
            geometry={nodes.honeybee3710_3.geometry}
            material={materials["Metal Pale Grey Edgewear.005"]}
          />
          <mesh /* gitar sapı */
            castShadow
            receiveShadow
            geometry={nodes.honeybee3710_4.geometry}
            material={sapMat}
          />
          <mesh /*gitar arkasındaki yer*/
            castShadow
            receiveShadow
            geometry={nodes.honeybee3710_5.geometry}
            material={nodes.honeybee3710_5.material}
          />
          <mesh /*gitar gövdesindeki metal yer*/
            castShadow
            receiveShadow
            geometry={nodes.honeybee3710_6.geometry}
            material={materials["Black painted metal.002"]}
          />
          <mesh /*gitar gövdesindeki plastik yer*/
            castShadow
            receiveShadow
            geometry={nodes.honeybee3710_7.geometry}
            material={props.material || turuncuMat}
          />
        </group>
      </group>

      
    
  );
}

useGLTF.preload("/gitarraaa.glb");
